[package]
name = "privatise-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
base64 = "0.22.1"
clap = { version = "4.5.35", features = ["derive"] }
reqwest = "0.12.15"
serde = "1.0.219"
serde_json = "1.0.140"
